"""
ComfyUI-SAM3 Nodes - Stateless Architecture

Version 3.0.0 refactoring:
- ComfyUI model management integration (ModelPatcher, load_models_gpu)
- Immutable video state (no global mutable state)
- Automatic cleanup (no manual SAM3CloseVideoSession needed)
"""

from .load_model import NODE_CLASS_MAPPINGS as LOAD_MODEL_MAPPINGS
from .load_model import NODE_DISPLAY_NAME_MAPPINGS as LOAD_MODEL_DISPLAY_MAPPINGS
from .segmentation import NODE_CLASS_MAPPINGS as SEGMENTATION_MAPPINGS
from .segmentation import NODE_DISPLAY_NAME_MAPPINGS as SEGMENTATION_DISPLAY_MAPPINGS
from .sam3_video_nodes import NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS
from .sam3_video_nodes import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_MAPPINGS
from .sam3_interactive import NODE_CLASS_MAPPINGS as INTERACTIVE_MAPPINGS
from .sam3_interactive import NODE_DISPLAY_NAME_MAPPINGS as INTERACTIVE_DISPLAY_MAPPINGS
from .sam3_auto_track import NODE_CLASS_MAPPINGS as AUTO_TRACK_MAPPINGS
from .sam3_auto_track import NODE_DISPLAY_NAME_MAPPINGS as AUTO_TRACK_DISPLAY_MAPPINGS
from .sam3_mask_tracks import NODE_CLASS_MAPPINGS as MASK_TRACKS_MAPPINGS
from .sam3_mask_tracks import NODE_DISPLAY_NAME_MAPPINGS as MASK_TRACKS_DISPLAY_MAPPINGS
from .sam3_progressive_batcher import NODE_CLASS_MAPPINGS as PROGRESSIVE_BATCHER_MAPPINGS
from .sam3_progressive_batcher import NODE_DISPLAY_NAME_MAPPINGS as PROGRESSIVE_BATCHER_DISPLAY_MAPPINGS
from .sam3_preset import NODE_CLASS_MAPPINGS as PRESET_MAPPINGS
from .sam3_preset import NODE_DISPLAY_NAME_MAPPINGS as PRESET_DISPLAY_MAPPINGS
from .sam3_utils import NODE_CLASS_MAPPINGS as UTILS_MAPPINGS
from .sam3_utils import NODE_DISPLAY_NAME_MAPPINGS as UTILS_DISPLAY_MAPPINGS

# Combine all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOAD_MODEL_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SEGMENTATION_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(INTERACTIVE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(AUTO_TRACK_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MASK_TRACKS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PROGRESSIVE_BATCHER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(PRESET_MAPPINGS)
NODE_CLASS_MAPPINGS.update(UTILS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_MODEL_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SEGMENTATION_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(INTERACTIVE_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AUTO_TRACK_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_TRACKS_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROGRESSIVE_BATCHER_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PRESET_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(UTILS_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
